### ISSUE TITLE
ImportError: cannot import name 'PointType' from 'semantic_sensor'

### ISSUE THREAD

**Issue by InsightofSPb** [ExistentialRobotics/SSMI#8]
Hello, I tried to start a mapping part. 
I've got a husky robot with realsense D435
While starting the `roslaunch semantic_octomap semantic_octomap.launch` I receive the next error:

```
process[semantic_cloud-1]: started with pid [51614]
process[semantic_octomap-2]: started with pid [51615]
[ INFO] [1701269714.376682262]: Semantic octomap generated!
Traceback (most recent call last):
  File "/home/s/test_f/devel/lib/semantic_octomap/semantic_sensor_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/s/test_f/src/SSMI-Mapping/scripts/semantic_sensor_node.py", line 17, in <module>
    from semantic_sensor import PointType, SemanticPclGenerator
ImportError: cannot import name 'PointType' from 'semantic_sensor' (/home/s/test_f/devel/.private/semantic_octomap/lib/semantic_octomap/semantic_sensor.py)
[semantic_cloud-1] process has died [pid 51614, exit code 1, cmd /home/s/test_f/devel/lib/semantic_octomap/semantic_sensor_node.py __name:=semantic_cloud __log:=/home/s/.ros/log/ffe73552-8ec6-11ee-8488-cfc925150467/semantic_cloud-1.log].
log file: /home/s/.ros/log/ffe73552-8ec6-11ee-8488-cfc925150467/semantic_cloud-1*.log

```
As I understand, classes from semantic_sensor.py are not imported, but I cannot get why it is happening. Files are in same folder, `catkin build / catkin_make` have been made. \
And  even log file is not created, I mean `log/......./semantic_cloud-1*.log`, so I cant check any additional information 😭 
\
![Screenshot from 2023-11-29 17-50-34](https://github.com/ExistentialRobotics/SSMI/assets/123558403/8345be03-f373-4cf7-87e3-dd302e9300e4)
\
What am I missing?

**Comment by tit006** [comment]
Should be fixed
